#include "middleware_classes.hpp"
#include "platforms/mapper.hpp"
#include "stm32f4xx_hal.h"
#include "uarm_lib.hpp"

#ifdef MW_ENABLE_CAN
#include "can.h"
#endif

#ifdef MW_ENABLE_I2C
#include "i2c.h"
#endif

#ifdef MW_ENABLE_SPI
#include "spi.h"
#endif

#ifdef MW_ENABLE_TIM
#include "tim.h"
#endif

namespace MW_BASE {
    bool Base::init() { return true; }

    void Base::delay_ms(uint32_t ms) {
        HAL_Delay(ms);
    }
}  // namespace MW_BASE

#ifdef MW_ENABLE_UART
#include "usart.h"
#endif

namespace MW_GPIO {
#ifdef MW_ENABLE_GPIO
    // Mapping functions between enum classes and HAL types.
    // ============================================================

    /**
     * @brief Convert the State enum to the corresponding HAL GPIO_PinState.
     * @param state The State enum value.
     * @return The corresponding GPIO_PinState value.
     */
    GPIO_PinState get_hal_state(State state) {
        switch (state) {
            case State::LOW:
                return GPIO_PIN_RESET;
            case State::HIGH:
                return GPIO_PIN_SET;
            default:
                ASSERT(false, "Unsupported GPIO pin state.");
        }
    }

    /**
     * @brief Convert the HAL GPIO_PinState to the State enum.
     * @param hal_state The HAL GPIO_PinState value.
     * @return The corresponding State enum value.
     */
    State get_state_from_hal(GPIO_PinState hal_state) {
        switch (hal_state) {
            case GPIO_PIN_RESET:
                return State::LOW;
            case GPIO_PIN_SET:
                return State::HIGH;
            default:
                ASSERT(false, "Unsupported HAL pin state.");
        }
    }

    bool GPIO::init() {
        return true;
    }

    /**
     * @brief Write a value to a GPIO pin.
     * @param port The GPIO port.
     * @param pin The GPIO pin.
     * @param state The desired state (HIGH or LOW) to write to the pin.
     */
    void GPIO::write_pin(Port port, Pin pin, State state) {
        HAL_GPIO_WritePin(platform::get_hal_gpio_port(port), platform::get_hal_gpio_pin(pin),
                          get_hal_state(state));
    }

    /**
     * @brief Read the value of a GPIO pin.
     * @param port The GPIO port.
     * @param pin The GPIO pin.
     * @return The current state (HIGH or LOW) of the pin.
     */
    State GPIO::read_pin(Port port, Pin pin) {
        return get_state_from_hal(
            HAL_GPIO_ReadPin(platform::get_hal_gpio_port(port), platform::get_hal_gpio_pin(pin)));
    }

    /**
     * @brief Toggle the state of a GPIO pin.
     * @param port The GPIO port.
     * @param pin The GPIO pin.
     */
    void GPIO::toggle_pin(Port port, Pin pin) {
        HAL_GPIO_TogglePin(platform::get_hal_gpio_port(port), platform::get_hal_gpio_pin(pin));
    }
#else
    bool GPIO::init() {
        ASSERT(false, "MW_GPIO is disabled for this base.");
        return false;
    }

    void GPIO::write_pin(Port port, Pin pin, State state) {
        (void) port;
        (void) pin;
        (void) state;
        ASSERT(false, "MW_GPIO is disabled for this base.");
    }

    State GPIO::read_pin(Port port, Pin pin) {
        (void) port;
        (void) pin;
        ASSERT(false, "MW_GPIO is disabled for this base.");
        return State::LOW;
    }

    void GPIO::toggle_pin(Port port, Pin pin) {
        (void) port;
        (void) pin;
        ASSERT(false, "MW_GPIO is disabled for this base.");
    }
#endif
}  // namespace MW_GPIO

namespace MW_TIM {
#ifdef MW_ENABLE_TIM
    bool TIM::init() {
        return true;
    }

    bool TIM::base_start(Timer timer, BaseStartMode mode) {
        TIM_HandleTypeDef* htim = platform::get_hal_tim(timer);
        switch (mode) {
            case BaseStartMode::Normal:
                return HAL_TIM_Base_Start(htim) == HAL_OK;
            case BaseStartMode::Interrupt:
                return HAL_TIM_Base_Start_IT(htim) == HAL_OK;
            default:
                ASSERT(false,
                       "Trying to use unsupported timer base start mode.");
        }
        return false;
    }

    /**
     * @brief Start PWM generation for a specific timer and channel.
     * @param[in] timer Timer to start.
     * @param[in] channel Channel of timer to start.
     */
    bool PWM::start(Timer timer, Channel channel) {
        return HAL_TIM_PWM_Start(platform::get_hal_tim(timer),
                                 platform::get_hal_tim_channel(channel)) == HAL_OK;
    }

    bool PWM::init() {
        return true;
    }

    /**
     * @brief Stop PWM generation for a specific timer and channel.
     * @param[in] timer Timer to stop.
     * @param[in] channel Channel of timer to stop.
     */
    void PWM::stop(Timer timer, Channel channel) {
        HAL_TIM_PWM_Stop(platform::get_hal_tim(timer),
                         platform::get_hal_tim_channel(channel));
    }

    /**
     * @brief Set the compare value of a PWM signal generated by a timer.
     * Changing the compare value directly affects the duty cycle of the PWM
     * signal generated. To calculate the exact compare value for a desired
     * duty cycle use this formula:
     * \f$\frac{compare_value}{TIMx->ARR + 1} * 100%\f$
     * @param[in] timer Timer to set.
     * @param[in] channel Channel of timer to set.
     * @param[in] compare_value The compare value for the PWM signal.
     */
    void PWM::set_compare(Timer timer, Channel channel, uint32_t compare) {
        __HAL_TIM_SET_COMPARE(platform::get_hal_tim(timer),
                              platform::get_hal_tim_channel(channel), compare);
    }

    void PWM::set_autoreload(Timer timer, uint32_t autoreload) {
        __HAL_TIM_SET_AUTORELOAD(platform::get_hal_tim(timer), autoreload);
    }

    void PWM::set_counter(Timer timer, uint32_t counter) {
        __HAL_TIM_SET_COUNTER(platform::get_hal_tim(timer), counter);
    }
#else
    bool TIM::init() {
        ASSERT(false, "MW_TIM is disabled for this base.");
        return false;
    }

    bool TIM::base_start(Timer timer, BaseStartMode mode) {
        (void) timer;
        (void) mode;
        ASSERT(false, "MW_TIM is disabled for this base.");
        return false;
    }

    bool PWM::start(Timer timer, Channel channel) {
        (void) timer;
        (void) channel;
        ASSERT(false, "MW_TIM is disabled for this base.");
        return false;
    }

    bool PWM::init() {
        ASSERT(false, "MW_TIM is disabled for this base.");
        return false;
    }

    void PWM::stop(Timer timer, Channel channel) {
        (void) timer;
        (void) channel;
        ASSERT(false, "MW_TIM is disabled for this base.");
    }

    void PWM::set_compare(Timer timer, Channel channel, uint32_t compare) {
        (void) timer;
        (void) channel;
        (void) compare;
        ASSERT(false, "MW_TIM is disabled for this base.");
    }

    void PWM::set_autoreload(Timer timer, uint32_t autoreload) {
        (void) timer;
        (void) autoreload;
        ASSERT(false, "MW_TIM is disabled for this base.");
    }

    void PWM::set_counter(Timer timer, uint32_t counter) {
        (void) timer;
        (void) counter;
        ASSERT(false, "MW_TIM is disabled for this base.");
    }
#endif
}  // namespace MW_TIM

namespace MW_CAN {
#ifdef MW_ENABLE_CAN
    /**
     * @brief Get the HAL FIFO value from the FIFO enum.
     * @param fifo The FIFO enum value.
     * @return The corresponding HAL FIFO value.
     */
    uint32_t get_hal_fifo(FIFO fifo) {
        switch (fifo) {
            case FIFO::FIFO_0:
                return CAN_RX_FIFO0;
            case FIFO::FIFO_1:
                return CAN_RX_FIFO1;
            default:
                ASSERT(false, "Unsupported CAN FIFO");
        }
    }

    bool CAN::init() {
        return true;
    }

    /**
     * @brief Send data over the CAN bus.
     * @pre 0 < length <= 8.
     * @param[in] bus The CAN bus to send data on.
     * @param[in] id The ID of the message to send.
     * @param[in] data The data to send.
     * @param[in] length The length of the data.
     */
    bool CAN::send_data(BUS bus, uint32_t id, uint32_t ext_id,
                        const uint8_t* data, uint32_t length) {
        // TODO implement sending extended ID messages.
        ASSERT(0 < length && length <= 8,
               "0 bytes < CAN data length <= 8 bytes.");
        CAN_TxHeaderTypeDef tx_header;
        switch (bus) {
            case BUS::CAN_1:
                [[fallthrough]];
            case BUS::CAN_2:
                tx_header.IDE = CAN_ID_STD;
                tx_header.StdId = id;
                tx_header.ExtId = 0;
                break;
            case BUS::CAN_1B:
                [[fallthrough]];
            case BUS::CAN_2B:
                tx_header.IDE = CAN_ID_EXT;
                tx_header.StdId = 0;
                tx_header.ExtId = ext_id;
                break;
        }
        tx_header.RTR = CAN_RTR_DATA;
        tx_header.DLC = length;
        return HAL_CAN_AddTxMessage(platform::get_hal_can(bus), &tx_header, data,
                                    nullptr) == HAL_OK;
    }

    /**
     * @brief Receive data from the CAN bus.
     * @param[in] bus The CAN bus to receive data from.
     * @param[in] fifo The FIFO to read from.
     * @param[out] id The ID of the received message.
     * @param[out] length The length of the received data.
     * @param[out] data The buffer to store the received data.
     */
    bool CAN::receive_data(BUS bus, FIFO fifo, uint32_t& id, uint32_t& ext_id,
                           uint8_t* dst, uint32_t& length) {
        // TODO implement receiving extended ID messages.
        CAN_RxHeaderTypeDef rx_header;
        if (HAL_CAN_GetRxMessage(platform::get_hal_can(bus), get_hal_fifo(fifo),
                                 &rx_header, dst) != HAL_OK) {
            return false;  // Error in receiving message
        } else {
            length = rx_header.DLC;

            if (rx_header.IDE == CAN_ID_EXT) {
                id = 0;
                ext_id = rx_header.ExtId;
            } else {
                id = rx_header.StdId;
                ext_id = 0;
            }

            return true;
        }
    }

    /**
     * @brief Start the CAN bus communication.
     * @param[in] bus The CAN bus to start.
     */
    bool CAN::start(BUS bus) {
        return HAL_CAN_Start(platform::get_hal_can(bus)) == HAL_OK;
    }

    /**
     * @brief Stop the CAN bus communication.
     * @param[in] bus The CAN bus to stop.
     */
    bool CAN::stop(BUS bus) {
        return HAL_CAN_Stop(platform::get_hal_can(bus)) == HAL_OK;
    }

    /**
     * @brief Activate a CAN notification.
     * @param[in] bus The CAN bus to activate the notification on.
     * @param[in] notification The notification type to activate.
     */
    bool CAN::activate_notification(BUS bus, Notification notification) {
        switch (notification) {
            case Notification::RX_FIFO0_MSG_PENDING:
                return HAL_CAN_ActivateNotification(
                           platform::get_hal_can(bus),
                           CAN_IT_RX_FIFO0_MSG_PENDING) == HAL_OK;
            default:
                ASSERT(false, "Unsupported CAN notification");
        }
    }

    /**
     * @brief Configure a CAN filter.
     * @param[in] bus The CAN bus to configure.
     * @param[in] filter_configuration The filter configuration to apply.
     */
    bool CAN::configure_filter(BUS bus, Filter filter_configuration) {
        CAN_FilterTypeDef filter_config;
        filter_config.FilterIdHigh = filter_configuration.id_high;
        filter_config.FilterIdLow = filter_configuration.id_low;
        filter_config.FilterMaskIdHigh = filter_configuration.mask_id_high;
        filter_config.FilterMaskIdLow = filter_configuration.mask_id_low;
        filter_config.FilterFIFOAssignment =
            get_hal_fifo(filter_configuration.fifo_assignment);
        filter_config.FilterBank = filter_configuration.filter_bank;
        filter_config.SlaveStartFilterBank =
            filter_configuration.slave_start_filter_bank;
        filter_config.FilterMode =
            (filter_configuration.mode == FilterMode::IDMask)
                ? CAN_FILTERMODE_IDMASK
                : CAN_FILTERMODE_IDLIST;
        filter_config.FilterActivation =
            (filter_configuration.is_activated) ? ENABLE : DISABLE;
        return HAL_CAN_ConfigFilter(platform::get_hal_can(bus), &filter_config) ==
               HAL_OK;
    }
#else
    bool CAN::init() {
        ASSERT(false, "MW_CAN is disabled for this base.");
        return false;
    }

    bool CAN::send_data(BUS bus, uint32_t id, uint32_t ext_id,
                        const uint8_t* data, uint32_t length) {
        (void) bus;
        (void) id;
        (void) ext_id;
        (void) data;
        (void) length;
        ASSERT(false, "MW_CAN is disabled for this base.");
        return false;
    }

    bool CAN::receive_data(BUS bus, FIFO fifo, uint32_t& id, uint32_t& ext_id,
                           uint8_t* dst, uint32_t& length) {
        (void) bus;
        (void) fifo;
        (void) id;
        (void) ext_id;
        (void) dst;
        (void) length;
        ASSERT(false, "MW_CAN is disabled for this base.");
        return false;
    }

    bool CAN::start(BUS bus) {
        (void) bus;
        ASSERT(false, "MW_CAN is disabled for this base.");
        return false;
    }

    bool CAN::stop(BUS bus) {
        (void) bus;
        ASSERT(false, "MW_CAN is disabled for this base.");
        return false;
    }

    bool CAN::activate_notification(BUS bus, Notification notification) {
        (void) bus;
        (void) notification;
        ASSERT(false, "MW_CAN is disabled for this base.");
        return false;
    }

    bool CAN::configure_filter(BUS bus, Filter filter_configuration) {
        (void) bus;
        (void) filter_configuration;
        ASSERT(false, "MW_CAN is disabled for this base.");
        return false;
    }
#endif
}  // namespace MW_CAN

namespace MW_UART {
#ifdef MW_ENABLE_UART
    bool UART::init() {
        return true;
    }

    /**
     * @brief Send data over UART.
     * @pre 0 < length <= MAX_UART_BUFFER_SIZE.
     * @param[in] uart The UART peripheral to send data on.
     * @param[in] data The data to send.
     * @param[in] length The length of the data.
     * @param[in] timeout The timeout for the transmission.
     */
    void UART::send_data(Peripheral uart, const uint8_t* data, uint32_t length,
                         uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot transfer data from nullptr.");
        HAL_UART_Transmit(platform::get_hal_uart(uart), data, length, timeout);
    }

    /**
     * @brief Send data over UART.
     * @pre 0 < length <= MAX_UART_BUFFER_SIZE.
     * @param[in] uart The UART peripheral to send data on.
     * @param[in] data The data to send.
     * @param[in] length The length of the data.
     * @param[in] timeout The timeout for the transmission.
     */
    void UART::send_data(Peripheral uart, std::span<const std::byte> data,
                         uint32_t timeout) {
        HAL_UART_Transmit(platform::get_hal_uart(uart),
                          reinterpret_cast<const uint8_t*>(data.data()),
                          data.size(), timeout);
    }

    /**
     * @brief Start reception of data from UART via DMA.
     * @pre 0 < length <= MAX_UART_BUFFER_SIZE
     * @param[in] uart The UART peripheral to receive data from.
     * @param[out] data The buffer to store the received data.
     * @param[out] length The length of the received data.
     * @return true if data was received successfully, false otherwise.
     */
    bool UART::receive_data(Peripheral uart, uint8_t* data, uint32_t length) {
        ASSERT(data != nullptr, "Cannot receive data to nullptr.");
        HAL_StatusTypeDef res =
            HAL_UART_Receive_DMA(platform::get_hal_uart(uart), data, length);
        return res == HAL_OK;  // Placeholder for actual implementation
    }

    /**
     * @brief Abort receiving data on the UART peripheral.
     * @param[in] uart The UART peripheral to abort receiving data on.
     */
    void UART::abort_receive(Peripheral uart) {
        HAL_UART_AbortReceive(platform::get_hal_uart(uart));
    }

    /**
     * @brief Abort transmitting data on the UART peripheral.
     * @param[in] uart The UART peripheral to abort.
     */
    void UART::abort_transmit(Peripheral uart) {
        HAL_UART_AbortTransmit(platform::get_hal_uart(uart));
    }

    void UART::clear_flags(Peripheral uart, uint32_t flags_to_clear) {
        __HAL_UART_CLEAR_FLAG(platform::get_hal_uart(uart), flags_to_clear);
    }
#else
    bool UART::init() {
        ASSERT(false, "MW_UART is disabled for this base.");
        return false;
    }

    void UART::send_data(Peripheral uart, const uint8_t* data, uint32_t length,
                         uint32_t timeout) {
        (void) uart;
        (void) data;
        (void) length;
        (void) timeout;
        ASSERT(false, "MW_UART is disabled for this base.");
    }

    void UART::send_data(Peripheral uart, std::span<const std::byte> data,
                         uint32_t timeout) {
        (void) uart;
        (void) data;
        (void) timeout;
        ASSERT(false, "MW_UART is disabled for this base.");
    }

    bool UART::receive_data(Peripheral uart, uint8_t* data, uint32_t length) {
        (void) uart;
        (void) data;
        (void) length;
        ASSERT(false, "MW_UART is disabled for this base.");
        return false;
    }

    void UART::abort_receive(Peripheral uart) {
        (void) uart;
        ASSERT(false, "MW_UART is disabled for this base.");
    }

    void UART::abort_transmit(Peripheral uart) {
        (void) uart;
        ASSERT(false, "MW_UART is disabled for this base.");
    }

    void UART::clear_flags(Peripheral uart, uint32_t flags_to_clear) {
        (void) uart;
        (void) flags_to_clear;
        ASSERT(false, "MW_UART is disabled for this base.");
    }
#endif
}  // namespace MW_UART

namespace MW_I2C {
#ifdef MW_ENABLE_I2C
    bool I2C::init() {
        return true;
    }

    void I2C::master_transmit(Periperhal i2c, uint8_t device_address,
                              const uint8_t* data, size_t size,
                              uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot transmit I2C data from nullptr.");
        HAL_I2C_Master_Transmit(
            platform::get_hal_i2c(i2c), static_cast<uint16_t>(device_address << 1),
            const_cast<uint8_t*>(data), static_cast<uint16_t>(size), timeout);
    }

    void I2C::master_receive(Periperhal i2c, uint8_t device_address,
                             uint8_t* data, size_t size, uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot receive I2C data to nullptr.");
        HAL_I2C_Master_Receive(platform::get_hal_i2c(i2c),
                               static_cast<uint16_t>(device_address << 1), data,
                               static_cast<uint16_t>(size), timeout);
    }

    void I2C::slave_transmit(Periperhal i2c, const uint8_t* data, size_t size,
                             uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot transmit I2C data from nullptr.");
        HAL_I2C_Slave_Transmit(platform::get_hal_i2c(i2c),
                               const_cast<uint8_t*>(data),
                               static_cast<uint16_t>(size), timeout);
    }

    void I2C::slave_receive(Periperhal i2c, uint8_t* data, size_t size,
                            uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot receive I2C data to nullptr.");
        HAL_I2C_Slave_Receive(platform::get_hal_i2c(i2c), data,
                              static_cast<uint16_t>(size), timeout);
    }

    void I2C::mem_write(Periperhal i2c, uint8_t device_address,
                        uint16_t memory_address, uint16_t memory_address_size,
                        const uint8_t* data, size_t size, uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot transmit I2C data from nullptr.");
        HAL_I2C_Mem_Write(
            platform::get_hal_i2c(i2c), static_cast<uint16_t>(device_address << 1),
            memory_address, memory_address_size, const_cast<uint8_t*>(data),
            static_cast<uint16_t>(size), timeout);
    }

    void I2C::mem_read(Periperhal i2c, uint8_t device_address,
                       uint16_t memory_address, uint16_t memory_address_size,
                       uint8_t* data, size_t size, uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot receive I2C data to nullptr.");
        HAL_I2C_Mem_Read(platform::get_hal_i2c(i2c),
                         static_cast<uint16_t>(device_address << 1),
                         memory_address, memory_address_size, data,
                         static_cast<uint16_t>(size), timeout);
    }
#else
    bool I2C::init() {
        ASSERT(false, "MW_I2C is disabled for this base.");
        return false;
    }

    void I2C::master_transmit(Periperhal i2c, uint8_t device_address,
                              const uint8_t* data, size_t size,
                              uint32_t timeout) {
        (void) i2c;
        (void) device_address;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_I2C is disabled for this base.");
    }

    void I2C::master_receive(Periperhal i2c, uint8_t device_address,
                             uint8_t* data, size_t size, uint32_t timeout) {
        (void) i2c;
        (void) device_address;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_I2C is disabled for this base.");
    }

    void I2C::slave_transmit(Periperhal i2c, const uint8_t* data, size_t size,
                             uint32_t timeout) {
        (void) i2c;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_I2C is disabled for this base.");
    }

    void I2C::slave_receive(Periperhal i2c, uint8_t* data, size_t size,
                            uint32_t timeout) {
        (void) i2c;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_I2C is disabled for this base.");
    }

    void I2C::mem_write(Periperhal i2c, uint8_t device_address,
                        uint16_t memory_address, uint16_t memory_address_size,
                        const uint8_t* data, size_t size, uint32_t timeout) {
        (void) i2c;
        (void) device_address;
        (void) memory_address;
        (void) memory_address_size;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_I2C is disabled for this base.");
    }

    void I2C::mem_read(Periperhal i2c, uint8_t device_address,
                       uint16_t memory_address, uint16_t memory_address_size,
                       uint8_t* data, size_t size, uint32_t timeout) {
        (void) i2c;
        (void) device_address;
        (void) memory_address;
        (void) memory_address_size;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_I2C is disabled for this base.");
    }
#endif
}  // namespace MW_I2C

namespace MW_SPI {
#ifdef MW_ENABLE_SPI
    bool SPI::init() {
        return true;
    }

    bool SPI::transmit(Peripheral spi, const uint8_t* data, size_t size,
                       uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot transmit SPI data from nullptr.");
        return HAL_SPI_Transmit(platform::get_hal_spi(spi), data,
                                static_cast<uint16_t>(size), timeout) == HAL_OK;
    }

    bool SPI::receive(Peripheral spi, uint8_t* data, size_t size,
                      uint32_t timeout) {
        ASSERT(data != nullptr, "Cannot receive SPI data to nullptr.");
        return HAL_SPI_Receive(platform::get_hal_spi(spi), data,
                               static_cast<uint16_t>(size), timeout) == HAL_OK;
    }

    bool SPI::transmit_receive(Peripheral spi, const uint8_t* tx, uint8_t* rx,
                               size_t size, uint32_t timeout) {
        ASSERT(tx != nullptr, "Cannot transmit SPI data from nullptr.");
        ASSERT(rx != nullptr, "Cannot receive SPI data to nullptr.");
        return HAL_SPI_TransmitReceive(platform::get_hal_spi(spi), tx, rx,
                                       static_cast<uint16_t>(size),
                                       timeout) == HAL_OK;
    }
#else
    bool SPI::init() {
        ASSERT(false, "MW_SPI is disabled for this base.");
        return false;
    }

    bool SPI::transmit(Peripheral spi, const uint8_t* data, size_t size,
                       uint32_t timeout) {
        (void) spi;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_SPI is disabled for this base.");
        return false;
    }

    bool SPI::receive(Peripheral spi, uint8_t* data, size_t size,
                      uint32_t timeout) {
        (void) spi;
        (void) data;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_SPI is disabled for this base.");
        return false;
    }

    bool SPI::transmit_receive(Peripheral spi, const uint8_t* tx, uint8_t* rx,
                               size_t size, uint32_t timeout) {
        (void) spi;
        (void) tx;
        (void) rx;
        (void) size;
        (void) timeout;
        ASSERT(false, "MW_SPI is disabled for this base.");
        return false;
    }
#endif
}  // namespace MW_SPI

namespace MW_RTOS {
#ifdef MW_ENABLE_RTOS
    bool RTOS::init() {
        CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
        DWT->CYCCNT = 0;
        DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
        return true;
    }

    bool RTOS::task_create(TaskHandle& task, const char* task_name,
                           TaskRoutine task_routine, void* task_arg,
                           size_t stack_depth, TaskPriority priority) {
        ASSERT(task_name != nullptr, "Task name cannot be nullptr.");
        ASSERT(task_routine != nullptr, "Task routine cannot be nullptr.");

        return xTaskCreate(task_routine, task_name,
                           static_cast<configSTACK_DEPTH_TYPE>(stack_depth),
                           task_arg, ToNativeTaskPriority(priority),
                           &task) == pdPASS;
    }

    void RTOS::critical_section_enter() {
        taskENTER_CRITICAL();
    }

    void RTOS::critical_section_exit() {
        taskEXIT_CRITICAL();
    }

    bool RTOS::event_group_create(EventGroupHandle& event_group) {
        event_group = xEventGroupCreate();
        return event_group != nullptr;
    }

    EventBits RTOS::event_group_set_bits(EventGroupHandle event_group,
                                         EventBits bits_to_set) {
        return static_cast<EventBits>(xEventGroupSetBits(
            event_group, static_cast<EventBits_t>(bits_to_set)));
    }

    EventBits RTOS::event_group_clear_bits(EventGroupHandle event_group,
                                           EventBits bits_to_clear) {
        return static_cast<EventBits>(xEventGroupClearBits(
            event_group, static_cast<EventBits_t>(bits_to_clear)));
    }

    EventBits RTOS::event_group_wait_bits(EventGroupHandle event_group,
                                          EventBits bits_to_wait_for,
                                          bool clear_on_exit,
                                          bool wait_for_all_bits,
                                          uint32_t ticks_to_wait) {
        return static_cast<EventBits>(xEventGroupWaitBits(
            event_group, static_cast<EventBits_t>(bits_to_wait_for),
            clear_on_exit ? pdTRUE : pdFALSE,
            wait_for_all_bits ? pdTRUE : pdFALSE,
            static_cast<TickType_t>(ticks_to_wait)));
    }

    EventBits RTOS::event_group_sync(EventGroupHandle event_group,
                                     EventBits bits_to_set,
                                     EventBits bits_to_wait_for,
                                     uint32_t ticks_to_wait) {
        return static_cast<EventBits>(
            xEventGroupSync(event_group, static_cast<EventBits_t>(bits_to_set),
                            static_cast<EventBits_t>(bits_to_wait_for),
                            static_cast<TickType_t>(ticks_to_wait)));
    }

    /**
     * @brief Delay until a certain tick count.
     * @param[in,out] previous_wake Pointer to the previous wake tick.
     * @param[in] ms Milliseconds to delay.
     */
    void RTOS::delay_until_ms(uint32_t* previous_wake, uint32_t ms) {
        *previous_wake = xTaskGetTickCount();
        TickType_t delay_ticks = pdMS_TO_TICKS(ms);
        vTaskDelayUntil(previous_wake, delay_ticks);
    }

    /**
     * @brief Delay for a certain number of milliseconds.
     * @param[in] ms Milliseconds to delay.
     */
    void RTOS::delay_ms(uint32_t ms) {
        TickType_t delay_ticks = pdMS_TO_TICKS(ms);
        vTaskDelay(delay_ticks);
    }

    void RTOS::delay_until_us(uint32_t* previous_wake, uint32_t us) {
        (void) previous_wake;
        (void) us;
        ASSERT(false, "Microsecond delays not implemented yet.");
        // TODO: Implement (AI - DO NOT IMPLEMENT)
        return;
    }

    void RTOS::delay_us(uint32_t us) {
        ASSERT(us < 10000,
               "Delays of 10ms or more should use delay_ms or delay_until_ms.");
        SystemCoreClockUpdate();
        uint32_t start_tick = DWT->CYCCNT;
        uint32_t delay_ticks = us * (SystemCoreClock / 1000000);
        while ((DWT->CYCCNT - start_tick) < delay_ticks) {}
    }

    /**
     * @brief Get the current RTOS tick.
     * @return The current tick count.
     */
    TickType RTOS::get_current_tick() {
        return static_cast<TickType>(HAL_GetTick());
    }

    TickType RTOS::ms_to_ticks(uint32_t ms) {
        return pdMS_TO_TICKS(ms);
    }

    /**
     * @brief Create a queue.
     * @param[out] queue The created queue handle.
     * @param[in] queue_length Number of items in the queue.
     * @param[in] item_size Size of each item.
     * @return true if creation failed, false otherwise.
     */
    bool RTOS::queue_create(QueueHandle& queue, size_t queue_length,
                            size_t item_size) {
        queue = xQueueCreate(queue_length, item_size);
        return queue == nullptr;
    }

    /**
     * @brief Overwrite the queue with new data.
     * @param[in] queue The queue handle.
     * @param[in] data_ptr Pointer to the data to write.
     * @return true if successful, false otherwise.
     */
    bool RTOS::queue_overwrite(QueueHandle queue, void* data_ptr) {
        return xQueueOverwrite(queue, data_ptr) == pdTRUE;
    }

    /**
     * @brief Push data to the back of the queue.
     * @param[in] queue The queue handle.
     * @param[in] data_ptr Pointer to the data to write.
     * @param[in] ticks_to_wait How long to wait if the queue is full.
     * @return true if successful, false otherwise.
     */
    bool RTOS::queue_pushback(QueueHandle queue, void* data_ptr,
                              TickType ticks_to_wait) {
        return xQueueSendToBack(queue, data_ptr, ticks_to_wait) == pdTRUE;
    }

    /**
     * @brief Overwrite the queue from ISR.
     * @param[in] queue The queue handle.
     * @param[in] data_ptr Pointer to the data to write.
     * @param[out] awakenHigherPrio Set to true if a higher priority task should be woken.
     * @return true if successful, false otherwise.
     */
    bool RTOS::queue_overwrite_from_isr(QueueHandle queue, void* data_ptr,
                                        bool* awakenHigherPrio) {
        BaseType_t awaken;
        BaseType_t result = xQueueOverwriteFromISR(queue, data_ptr, &awaken);
        if (awakenHigherPrio != nullptr) {
            *awakenHigherPrio = awaken == pdTRUE;
        }
        return result == pdTRUE;
    }

    /**
     * @brief Push data to the back of the queue from ISR.
     * @param[in] queue The queue handle.
     * @param[in] data_ptr Pointer to the data to write.
     * @param[out] awakenHigherPrio Set to true if a higher priority task should be woken.
     * @return true if successful, false otherwise.
     */
    bool RTOS::queue_pushback_from_isr(QueueHandle queue, void* data_ptr,
                                       bool* awakenHigherPrio) {
        BaseType_t awaken;
        BaseType_t result = xQueueSendFromISR(queue, data_ptr, &awaken);
        if (awakenHigherPrio != nullptr) {
            *awakenHigherPrio = awaken == pdTRUE;
        }
        return result == pdTRUE;
    }

    /**
     * @brief Peek at the front of the queue.
     * @param[in] queue The queue handle.
     * @param[out] data_ptr Pointer to the data to read.
     * @param[in] ticks_to_wait How long to wait if the queue is empty.
     * @return true if successful, false otherwise.
     */
    bool RTOS::queue_peek(QueueHandle queue, void* data_ptr,
                          TickType ticks_to_wait) {
        return xQueuePeek(queue, data_ptr, ticks_to_wait) == pdTRUE;
    }

    /**
     * @brief Get data from the front of the queue.
     * @param[in] queue The queue handle.
     * @param[out] data_ptr Pointer to the data to read.
     * @param[in] ticks_to_wait How long to wait if the queue is empty.
     * @return true if successful, false otherwise.
     */
    bool RTOS::queue_get(QueueHandle queue, void* data_ptr,
                         TickType ticks_to_wait) {
        return xQueueReceive(queue, data_ptr, ticks_to_wait) == pdTRUE;
    }
#else
    bool RTOS::init() {
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    bool RTOS::task_create(TaskHandle& task, const char* task_name,
                           TaskRoutine task_routine, void* task_arg,
                           size_t stack_depth, TaskPriority priority) {
        (void) task;
        (void) task_name;
        (void) task_routine;
        (void) task_arg;
        (void) stack_depth;
        (void) priority;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    void RTOS::critical_section_enter() {
        ASSERT(false, "MW_RTOS is disabled for this base.");
    }

    void RTOS::critical_section_exit() {
        ASSERT(false, "MW_RTOS is disabled for this base.");
    }

    bool RTOS::event_group_create(EventGroupHandle& event_group) {
        (void) event_group;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    EventBits RTOS::event_group_set_bits(EventGroupHandle event_group,
                                         EventBits bits_to_set) {
        (void) event_group;
        (void) bits_to_set;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return 0;
    }

    EventBits RTOS::event_group_clear_bits(EventGroupHandle event_group,
                                           EventBits bits_to_clear) {
        (void) event_group;
        (void) bits_to_clear;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return 0;
    }

    EventBits RTOS::event_group_wait_bits(EventGroupHandle event_group,
                                          EventBits bits_to_wait_for,
                                          bool clear_on_exit,
                                          bool wait_for_all_bits,
                                          uint32_t ticks_to_wait) {
        (void) event_group;
        (void) bits_to_wait_for;
        (void) clear_on_exit;
        (void) wait_for_all_bits;
        (void) ticks_to_wait;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return 0;
    }

    EventBits RTOS::event_group_sync(EventGroupHandle event_group,
                                     EventBits bits_to_set,
                                     EventBits bits_to_wait_for,
                                     uint32_t ticks_to_wait) {
        (void) event_group;
        (void) bits_to_set;
        (void) bits_to_wait_for;
        (void) ticks_to_wait;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return 0;
    }

    void RTOS::delay_until_ms(uint32_t* previous_wake, uint32_t ms) {
        (void) previous_wake;
        (void) ms;
        ASSERT(false, "MW_RTOS is disabled for this base.");
    }

    void RTOS::delay_ms(uint32_t ms) {
        (void) ms;
        ASSERT(false, "MW_RTOS is disabled for this base.");
    }

    void RTOS::delay_until_us(uint32_t* previous_wake, uint32_t us) {
        (void) previous_wake;
        (void) us;
        ASSERT(false, "MW_RTOS is disabled for this base.");
    }

    void RTOS::delay_us(uint32_t us) {
        (void) us;
        ASSERT(false, "MW_RTOS is disabled for this base.");
    }

    TickType RTOS::get_current_tick() {
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return 0;
    }

    TickType RTOS::ms_to_ticks(uint32_t ms) {
        (void) ms;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return 0;
    }

    bool RTOS::queue_create(QueueHandle& queue, size_t queue_length,
                            size_t item_size) {
        (void) queue;
        (void) queue_length;
        (void) item_size;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    bool RTOS::queue_overwrite(QueueHandle queue, void* data_ptr) {
        (void) queue;
        (void) data_ptr;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    bool RTOS::queue_pushback(QueueHandle queue, void* data_ptr,
                              TickType ticks_to_wait) {
        (void) queue;
        (void) data_ptr;
        (void) ticks_to_wait;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    bool RTOS::queue_overwrite_from_isr(QueueHandle queue, void* data_ptr,
                                        bool* awakenHigherPrio) {
        (void) queue;
        (void) data_ptr;
        (void) awakenHigherPrio;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    bool RTOS::queue_pushback_from_isr(QueueHandle queue, void* data_ptr,
                                       bool* awakenHigherPrio) {
        (void) queue;
        (void) data_ptr;
        (void) awakenHigherPrio;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    bool RTOS::queue_peek(QueueHandle queue, void* data_ptr,
                          TickType ticks_to_wait) {
        (void) queue;
        (void) data_ptr;
        (void) ticks_to_wait;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }

    bool RTOS::queue_get(QueueHandle queue, void* data_ptr,
                         TickType ticks_to_wait) {
        (void) queue;
        (void) data_ptr;
        (void) ticks_to_wait;
        ASSERT(false, "MW_RTOS is disabled for this base.");
        return false;
    }
#endif
}  // namespace MW_RTOS