add_library(SSD1306_DRIVER2 STATIC ssd1306_driver.cpp)
target_include_directories(SSD1306_DRIVER2 PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(SSD1306_DRIVER2 PUBLIC MW::MIDDLEWARE)
add_library(FW::DEVICE::SSD1306_DRIVER2 ALIAS SSD1306_DRIVER2)

add_library(BUZZER STATIC buzzer.cpp)
target_include_directories(BUZZER PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(BUZZER PUBLIC MW::MIDDLEWARE)

add_library(BMI088_DRIVER_CPP INTERFACE)
target_include_directories(BMI088_DRIVER_CPP INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(BMI088_DRIVER_CPP INTERFACE MW::MIDDLEWARE)
add_library(MODULES::BMI088_DRIVER ALIAS BMI088_DRIVER_CPP)

add_library(IST8310_DRIVER_CPP INTERFACE)
target_include_directories(IST8310_DRIVER_CPP INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(IST8310_DRIVER_CPP INTERFACE MW::MIDDLEWARE)
add_library(MODULES::IST8310_DRIVER ALIAS IST8310_DRIVER_CPP)

add_library(ISOTP INTERFACE)
target_include_directories(ISOTP INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(ISOTP INTERFACE LIB::UARM_LIB)
add_library(MODULES::ISOTP ALIAS ISOTP)

add_library(MESSAGE_CENTER INTERFACE)
target_include_directories(MESSAGE_CENTER INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(MESSAGE_CENTER 
    INTERFACE
        SUBSYSTEMS_INCLUDE
        LIB::UARM_OS
        LIB::UARM_LIB
        MW::MIDDLEWARE)
add_library(MODULES::MESSAGE_CENTER ALIAS MESSAGE_CENTER)

add_library(UC_UART INTERFACE)
target_include_directories(UC_UART INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(UC_UART INTERFACE LIB::UARM_LIB)
add_library(MODULES::UC_UART ALIAS UC_UART)

add_library(SIMPLE_COMM INTERFACE)
target_include_directories(SIMPLE_COMM INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(SIMPLE_COMM 
    INTERFACE 
        ALGORITHMS::FIFO
        LIB::UARM_LIB
        MW::MIDDLEWARE)
add_library(MODULES::SIMPLE_COMM ALIAS SIMPLE_COMM)

add_library(DEBUG INTERFACE)
target_include_directories(DEBUG INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(DEBUG 
    INTERFACE 
        LIB::UARM_LIB
        MW::MIDDLEWARE)
add_library(MODULES::DEBUG ALIAS DEBUG)