add_library(FAKE_MESSAGE_CENTER INTERFACE)
target_include_directories(FAKE_MESSAGE_CENTER 
    INTERFACE
        ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(FAKE_MESSAGE_CENTER 
    INTERFACE
        MODULES::MESSAGE_CENTER
        MW::MIDDLEWARE)
add_library(LIB::FAKE_MESSAGE_CENTER ALIAS FAKE_MESSAGE_CENTER)

add_library(FAKE_UART INTERFACE)
target_include_directories(FAKE_UART 
    INTERFACE
        ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(FAKE_UART 
    INTERFACE
        MW::MIDDLEWARE)
add_library(LIB::FAKE_UART ALIAS FAKE_UART)
add_library(FAKE_CHASSIS_DRIVE INTERFACE)
target_include_directories(FAKE_CHASSIS_DRIVE 
    INTERFACE
        ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(FAKE_CHASSIS_DRIVE 
    INTERFACE
        APPS_INCLUDE)
add_library(LIB::FAKE_CHASSIS_DRIVE ALIAS FAKE_CHASSIS_DRIVE)
