set(ALGORITHMS_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Algorithms)
set(APPLICATIONS_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Applications)
set(FIRMWARE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Firmware)
set(LIB_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Lib)
set(SUBSYSTEMS_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Subsystems)
set(CONFIGS_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Configs)

if (${CMAKE_BUILD_TYPE} STREQUAL "GTest")
    add_subdirectory(Lib)
    add_subdirectory(Algorithms)
    add_subdirectory(Subsystems)
    add_subdirectory(Applications)
else()
    add_subdirectory(Lib)
    add_subdirectory(Algorithms)
    add_subdirectory(Firmware)
    add_subdirectory(Subsystems)
    add_subdirectory(Applications)
    add_subdirectory(ISRs)
endif()
