name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build_type: GTest
            os: ubuntu-24.04
            c_compiler: gcc-13
            cpp_compiler: g++-13
            toolchain_install: |
              sudo apt-get update -qq
              sudo apt-get install -y gcc-13 g++-13 ninja-build

          - build_type: Mecanum
            os: ubuntu-24.04
            c_compiler: arm-none-eabi-gcc
            cpp_compiler: arm-none-eabi-g++
            toolchain_install: |
              sudo apt-get update -qq
              sudo apt-get install -y gcc-arm-none-eabi ninja-build
          - build_type: Omni
            os: ubuntu-24.04
            c_compiler: arm-none-eabi-gcc
            cpp_compiler: arm-none-eabi-g++
            toolchain_install: |
              sudo apt-get update -qq
              sudo apt-get install -y gcc-arm-none-eabi ninja-build
          - build_type: Swerve
            os: ubuntu-24.04
            c_compiler: arm-none-eabi-gcc
            cpp_compiler: arm-none-eabi-g++
            toolchain_install: |
              sudo apt-get update -qq
              sudo apt-get install -y gcc-arm-none-eabi ninja-build
          - build_type: Hero
            os: ubuntu-24.04
            c_compiler: arm-none-eabi-gcc
            cpp_compiler: arm-none-eabi-g++
            toolchain_install: |
              sudo apt-get update -qq
              sudo apt-get install -y gcc-arm-none-eabi ninja-build

    env:
      CC: ${{ matrix.c_compiler }}
      CXX: ${{ matrix.cpp_compiler }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Toolchain
      shell: bash
      run: ${{ matrix.toolchain_install }}

    - name: Verify Compilers
      shell: bash
      run: |
        $CC --version
        $CXX --version

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build-${{ matrix.build_type }}" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -G Ninja -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config --rerun-failed --output-on-failure ${{ matrix.build_type }}